Renamed modules and tidied internal imports.
thisiswhereitype/gmlp pull request #5
Opened 2016-10-13 14:44 UTC by thisiswhereitype

Renamed files to more obvious names, vhdlWriter is now imported though Writers/Write.hs

2016-10-13 15:21 UTC, snowleopard requested changes
I've added a bunch of comments, however, now I'm thinking that `Parser.X` and `Writer.Y` may not be a good choice for module names, since it may conflict with other Haskell libraries that do parsing. 

What about using `Pangraph` as the top-level module name? For example, `Pangraph.Parser.Workcraft`? Or, if it feels too long, perhaps `Pangraph.Workcraft` and this module will take care both of parser and writer. Similarly, `Pangraph.GraphML` and `Pangraph.Vhdl`.

2016-10-13 15:21 UTC, snowleopard commented on pangraph.cabal
> +  other-modules:       Parsers.GmlParser
While we are renaming things, I'd recommend using a full name for this parser: `GraphMLParser`. I find `Gml` a bit too cryptic.

2016-10-13 15:21 UTC, snowleopard commented on pangraph.cabal
> +  other-modules:       Parsers.GmlParser
On a second thought, it probably make sense to use this naming convention: `Parser.GraphML` -- no need to repeat the word `Parser` twice. Also note, that usually Haskell modules are not plural, so `Parser`, not `Parsers`.

2016-10-13 15:21 UTC, snowleopard commented on pangraph.cabal
> +                     , Parsers.WorkParser
Here, we can then use `Parser.Workcraft`.

2016-10-13 15:21 UTC, snowleopard commented on pangraph.cabal
> +                     , Parsers.Parser
Why not simply `Parser`?

2016-10-13 15:21 UTC, snowleopard commented on pangraph.cabal
> +                     , Writers.Writer
Why not simply `Writer`?

2016-10-13 15:21 UTC, snowleopard commented on pangraph.cabal
>                       , Writers.VhdlWriter
This one becomes `Writer.Vhdl`.

2016-10-13 19:31 UTC, thisiswhereitype commented
So to get this right a parser and writer for graphML should be in `pangraph/graphML` and the front level interface given by `Pangraph.hs`. One of my goals is that any supported file can be parsed or read by the same function.

2016-10-13 22:47 UTC, snowleopard commented
> So to get this right a parser and writer for graphML should be in `pangraph/graphML` and the front level interface given by `Pangraph.hs`. 

Just to be precise: both the parser and the writer for graphML will live in `src/Pangraph/GraphML.hs`, while the top-level interface will live in `src/Pangraph.hs`.

> One of my goals is that any supported file can be parsed or read by the same function.

I'm not sure I understand what you mean, but I guess it's fine to have functions called `parse` and `write` both in `Pangraph.GraphML` and `Pangraph.Workcraft`, so people can call them using qualified names, e.g. as `GraphML.parse`, `GraphML.write`, `Workcraft.parse`, etc.

2016-10-14 14:02 UTC, thisiswhereitype commented
I agree with the compartment scheme, but I would like the export a smaller API that will choose the parser or writer based on the file type given in a path. Although I see it may be useful to expose each writer and parser in the API directly but it is not currently. Do you think this is useful?

2016-10-14 14:46 UTC, snowleopard commented
The simplest and most useful API for a parser/writer are functions: `String -> Graph` and `Graph -> String`, where `Graph` is your internal graph representation. (The `String` datatype is actually very inefficient for representing large strings, but let's not worry about this for now.)

Anything more clever than this, for example, parsing a graph `FilePath -> IO Graph`, or detecting the right parser from the file extension will actually get in the way of using the parsers in many situations:
* What if I only have a string, not a file? Say, I received the string from network. Do I have to write it to a file first in order to use the parser?
* What if my file has extension `xyz` instead of `graphml`? Do I need to rename it first?

So, for the library `pangraph` I'm not even sure it's important to have any top-level module that re-exports some kind of unified API to use all parsers. Individual APIs like `Pangraph.GraphML` will work fine.

As for the executable `pangraph` -- it will import all these various parsers and may indeed benefit from automated detection of file types by looking at file extensions. But this doesn't have to be in the API of the `pangraph` library itself.

2016-10-16 10:07 UTC, thisiswhereitype commented
Okay I see where you are coming from, I will have to move some things around but that is possible to implement. I will maintain the unified interface and I think some arguments could be passed to implement the ignoring of parsers or do you think I should ignore this feature for now?

2016-10-16 12:57 UTC, snowleopard commented
> or do you think I should ignore this feature for now?

As I mentioned, I don't think a unified interface is a feature for the library. It is more of a bug :-)

When you use `pangraph` as a library, you always know exactly what you need to parse (for example, in our drug discovery project we know that we need to parse GraphML files and write VHDL files), so no automation is needed -- we just import the right modules and use them by calling the `parse` and `write` functions. A unified interface is likely to be both a maintenance burden for the library developers, as well as an unnecessary complication of the API for potential users.

2016-10-16 13:00 UTC, snowleopard commented
Just to add: automation is certainly useful for the `pangraph` executable -- that's exactly where it needs to live, in the executable source, not in the `pangraph` library.

2016-10-19 19:00 UTC, snowleopard commented
@thisiswhereitype Why do we have so many commented-out lines of code? If they are not currently needed, let's just remove them. Otherwise, they make it hard to read the code.

2016-10-20 07:33 UTC, thisiswhereitype commented
Most of the commented code is for modules and features which are to be moved to the executable, e.g. hiding the unified interface.

2016-10-20 11:01 UTC, snowleopard commented
@thisiswhereitype There is no benefit in committing commented out code. Simply delete it -- it will always be waiting for you in the git history (just rollback to a previous commit), where you can copy it if you like.

2016-10-20 13:32 UTC, thisiswhereitype commented
Okay I am currently implementing letting the user handle the errors rather then raising an exception, I remove offending code in the next commit.

2016-10-24 10:33 UTC, snowleopard commented
Thanks @thisiswhereitype! Would you like to do any further changes or is this ready to be merged?

2016-10-24 10:59 UTC, thisiswhereitype commented
Please wait for me to update the docs then I think this pull request will be finished.

2016-10-24 20:11 UTC, thisiswhereitype commented
Please merge if you see fit.

2016-10-24 20:55 UTC, merged

2016-10-24 20:55 UTC, snowleopard commented
Thanks @thisiswhereitype! Merged now.